FROM ubuntu:20.04
MAINTAINER Chris Gibson

RUN apt-get update -y && apt-get install -y python3
RUN apt-get install -y python3-pip

RUN python3 -m pip install -U pysqlite3-binary

RUN apt-get install -y git
WORKDIR /root/
RUN git clone https://github.com/electrumsv/electrumsv.git

RUN export PATH=/root/.local/bin:$PATH

WORKDIR /root/electrumsv
RUN pip3 install --user -r contrib/deterministic-build/requirements.txt
RUN pip3 install --user -r contrib/deterministic-build/requirements-binaries.txt

#RUN pip3 install --user -r contrib/deterministic-build/requirements-hw.txt
