FROM centos:7
MAINTAINER Chris Gibson

RUN yum -y update 
RUN yum -y install wget  

RUN wget -O bsv-0.2.1.tar.gz https://download.bitcoinsv.io/bitcoinsv/0.2.1/bitcoin-sv-0.2.1-x86_64-linux-gnu.tar.gz
RUN tar -xzvf bsv-0.2.1.tar.gz

RUN wget -O bsv-0.2.2.beta.tar.gz https://download.bitcoinsv.io/bitcoinsv/0.2.2.beta/bitcoin-sv-0.2.2.beta-x86_64-linux-gnu.tar.gz
RUN tar -xzvf bsv-0.2.2.beta.tar.gz

RUN wget -O bsv-1.0.0.tar.gz https://download.bitcoinsv.io/bitcoinsv/1.0.0/bitcoin-sv-1.0.0-x86_64-linux-gnu.tar.gz
RUN tar -xzvf bsv-1.0.0.tar.gz

RUN wget -O bsv-1.0.1.tar.gz https://download.bitcoinsv.io/bitcoinsv/1.0.1/bitcoin-sv-1.0.1-x86_64-linux-gnu.tar.gz
RUN tar -xzvf bsv-1.0.1.tar.gz

RUN wget -O bsv-1.0.2.tar.gz https://download.bitcoinsv.io/bitcoinsv/1.0.2/bitcoin-sv-1.0.2-x86_64-linux-gnu.tar.gz
RUN tar -xzvf bsv-1.0.2.tar.gz

RUN wget -O bsv-1.0.3.tar.gz https://download.bitcoinsv.io/bitcoinsv/1.0.3/bitcoin-sv-1.0.3-x86_64-linux-gnu.tar.gz
RUN tar -xzvf bsv-1.0.3.tar.gz




