FROM ubuntu:20.04

RUN apt-get update -y

RUN echo "set -o vi" >> /root/.bashrc
RUN echo "source .bashrc" >> /root/.bash_profile

ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#RUN apt upgrade -y && apt install bpftrace -y

RUN apt-get upgrade -y && apt-get install libbpfcc-dev -y

#RUN apt-get install -y g++ libfl-dev systemtap-sdt-dev llvm-7-dev llvm-7-runtime \
#    libclang-7-dev clang-7 
#
#ENV HOME=/root
#WORKDIR $HOME
#RUN git clone https://github.com/iovisor/bpftrace
#RUN mkdir bpftrace/build
#WORKDIR bpftrace/build
#RUN cmake -DCMAKE_BUILD_TYPE=Release ..
#RUN make
#RUN make install

WORKDIR /root
RUN apt-get update
RUN apt-get install -y bison cmake flex g++ git libelf-dev zlib1g-dev libfl-dev systemtap-sdt-dev binutils-dev
RUN apt-get install -y llvm-7-dev llvm-7-runtime libclang-7-dev clang-7
RUN git clone https://github.com/iovisor/bpftrace
RUN mkdir bpftrace/build
RUN cd bpftrace/build
RUN pwd
RUN ls
RUN cmake -DCMAKE_BUILD_TYPE=Release /root/bpftrace/
#RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make -j8
RUN make install



