FROM ubuntu_dev

RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    libdb-dev \
    libdb++-dev \
    build-essential \
    libtool \
    autotools-dev \
    automake \
    pkg-config \
    libssl-dev \
    libevent-dev \
    libminiupnpc-dev \
    libzmq3-dev \
    bsdmainutils 

