RUN mkdir /root/.bitcoin
WORKDIR /root/.bitcoin
COPY cargo/bitcoin.conf .
COPY cargo/bitcoin-cli.conf .

RUN apt-get update -y && apt-get install -y iproute2

ENTRYPOINT ["/root/sv/build/v1.0.5/release/src/bitcoind"]


