FROM dev_ubuntu:18.04

RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    libdb-dev \
    libdb++-dev \
    build-essential \
    libtool \
    autotools-dev \
    automake \
    pkg-config \
    libssl-dev \
    libevent-dev \
    libminiupnpc-dev \
    libzmq3-dev \
    bsdmainutils \
    curl \
    unzip \
    libcrypto++6 

RUN curl https://rea.crea.si/download/nchain/gateway/TxBlaster6_2.zip -O

RUN unzip /TxBlaster6_2.zip

RUN chmod +x /TxBlaster6/bin/ubuntu18/TxBlaster

EXPOSE 8332 18332 18444

RUN mkdir /root/.bitcoin
RUN echo "excessiveblocksize=0" >> /root/.bitcoin/bitcoin.conf
RUN echo "maxstackmemoryusageconsensus=0" >> /root/.bitcoin/bitcoin.conf

RUN echo "regtest=1" >> /root/.bitcoin/bitcoin.conf


