FROM ubuntu:20.04
MAINTAINER Chris Gibson

RUN apt-get update && apt-get install --yes 

RUN apt-get -y install bison build-essential cmake flex git libedit-dev \
  libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev

RUN apt install -y linux-headers-$(uname -r) 

RUN git clone https://github.com/iovisor/bcc.git
RUN mkdir bcc/build
WORKDIR bcc/build
RUN cmake ..
RUN make
RUN make install
RUN cmake -DPYTHON_CMD=python .. # build python3 binding
WORKDIR src/python/
RUN make
RUN make install

RUN apt-get install -y g++ libfl-dev systemtap-sdt-dev llvm-7-dev llvm-7-runtime \
    libclang-7-dev clang-7 

ENV HOME=/root
WORKDIR $HOME
RUN git clone https://github.com/iovisor/bpftrace
RUN mkdir bpftrace/build
WORKDIR bpftrace/build
RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make
RUN make install




