FROM ubuntu:20.04

RUN apt-get update -y

RUN echo "set -o vi" >> /root/.bashrc
RUN echo "source .bashrc" >> /root/.bash_profile

RUN apt upgrade -y && apt install bpftrace -y

#RUN apt-get install -y g++ libfl-dev systemtap-sdt-dev llvm-7-dev llvm-7-runtime \
#    libclang-7-dev clang-7 
#
#ENV HOME=/root
#WORKDIR $HOME
#RUN git clone https://github.com/iovisor/bpftrace
#RUN mkdir bpftrace/build
#WORKDIR bpftrace/build
#RUN cmake -DCMAKE_BUILD_TYPE=Release ..
#RUN make
#RUN make install

