FROM centos:7
MAINTAINER Chris Gibson

RUN yum -y update && yum -y install \
	less \  
	build-essential	\
RUN yum    vim \
RUN yum -y install    git 
RUN yum -y install    subversion 
RUN yum -y install    clang 
RUN yum -y install    cmake 
RUN yum -y install    python3 
RUN yum -y install    tmux 
RUN yum -y install    cscope 
RUN yum -y install    gdb 
RUN yum -y install    valgrind 
RUN yum -y install    lldb 

RUN git clone https://github.com/chrisgibson01/git.git /root/git.git
RUN ln -s /root/git.git/.gitconfig /root/.gitconfig
RUN ln -s /root/git.git/.gitignore /root/.gitignore

RUN git clone https://github.com/chrisgibson01/vim.git /root/vim.git
RUN ln -s /root/vim.git/.vimrc /root/.vimrc

RUN git clone https://github.com/chrisgibson01/tmux.git /root/tmux.git
RUN ln -s /root/tmux.git/.tmux.conf /root/.tmux.conf

RUN echo "set -o vi" >> /root/.bashrc
RUN echo "source .bashrc" >> /root/.bash_profile

RUN git clone https://github.com/chrisgibson01/gdb.git /root/gdb.git
RUN ln -s /root/gdb.git/.gdbinit /root/.gdbinit

#RUN svn checkout svn://gcc.gnu.org/svn/gcc/trunk/libstdc++-v3/python /root/gdb_printers/python

#RUN git clone https://github.com/chrisgibson01/wireshark.git /root/wireshark.git

#RUN git clone https://github.com/google/benchmark.git /root/benchmark
#RUN git clone https://github.com/google/googletest.git /root/benchmark/googletest
#RUN mkdir /root/benchmark/build && cd /root/benchmark/build

#RUN pip install --upgrade pip
#RUN pip install sphinx

##RUN cmake /root/benchmark/
##RUN cmake --build .

##RUN git clone https://github.com/google/benchmark.git
##RUN git clone https://github.com/google/googletest.git benchmark/googletest 
##RUN mkdir build && cd build
##RUN cmake ../benchmark
##RUN make





