FROM ubuntu:18.04
MAINTAINER Chris Gibson

RUN apt-get update && apt-get install --yes 

RUN apt-get -y install bison build-essential cmake flex git libedit-dev \
  libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev

RUN apt install -y linux-headers-$(uname -r) 

RUN git clone https://github.com/iovisor/bcc.git
RUN mkdir bcc/build
WORKDIR bcc/build
RUN cmake ..
RUN make
RUN make install
RUN cmake -DPYTHON_CMD=python .. # build python3 binding
WORKDIR src/python/
RUN make
RUN make install


WORKDIR /usr/share/bcc

