FROM bsv_dev_ubuntu:18.04

RUN apt update && apt install -y \
    curl \
    unzip \
    libcrypto++6 \
    libboost-all-dev 

WORKDIR /root

RUN curl https://rea.crea.si/download/nchain/gateway/TxBlaster6_2.zip -O

RUN unzip /root/TxBlaster6_2.zip

RUN find / -iname txblaster

RUN chmod +x /root/TxBlaster6/bin/ubuntu18/TxBlaster

EXPOSE 8332 18332 18444

RUN echo "regtest=1" >> /root/.bitcoin/bitcoin.conf
RUN echo "datadir=/root/.bitcoin" >> /root/.bitcoin/bitcoin.conf

RUN echo "port=11150" >> /root/.bitcoin/bitcoin.conf
RUN echo "rpcport=11151" >> /root/.bitcoin/bitcoin.conf
RUN echo "rpcuser=user" >> /root/.bitcoin/bitcoin.conf
RUN echo "rpcpassword=password" >> /root/.bitcoin/bitcoin.conf
RUN echo "daemon=1" >> /root/.bitcoin/bitcoin.conf
RUN echo "discover=0" >> /root/.bitcoin/bitcoin.conf
RUN echo "listenonion=0" >> /root/.bitcoin/bitcoin.conf
RUN echo "usecashaddr=0" >> /root/.bitcoin/bitcoin.conf
RUN echo "debug=1" >> /root/.bitcoin/bitcoin.conf
RUN echo "debugexclude=libevent" >> /root/.bitcoin/bitcoin.conf
RUN echo "debugexclude=leveldb" >> /root/.bitcoin/bitcoin.conf

